env:
  browser: false
extends: 'eslint:recommended'
parserOptions:
  sourceType: 'module'
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
plugins:
  - react
rules:
  react/jsx-uses-vars: ["error"]
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - always
